apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
  namespace: build
spec:
  timeout: 20m
  serviceAccountName: knative-build-bot
  source:
    git:
      url: $CI_PROJECT_URL
      revision: $CI_COMMIT_REF_NAME
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=/workspace/Dockerfile
    - --destination=dudaji/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - --destination=dudaji/$CI_PROJECT_NAME:latest
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker

